# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: feetech_arm
  joint_model_group_pose: home_arm
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 30
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - headjoint_8
    - headjoint_9
    - joint_0
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20
controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
#  - name: waist_position_controller
#    action_ns: follow_joint_trajectory
#    type: FollowJointTrajectory
#    default: true
#    joints:
#      - joint_0
  - name: head_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - headjoint_8
      - headjoint_9
initial:  # Define initial robot poses.
  - group: feetech_arm
    pose: home_arm
  - group: feetech_waist
    pose: home_waist
  - group: feetech_head
    pose: home_head

