joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 20

arm_position_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
    - joint_0
#waist_position_controller:
#  type: "position_controllers/JointTrajectoryController"
#  joints:
#    - joint_0

head_position_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - headjoint_8
    - headjoint_9
