feetech_arm:
     loop_hz: 30 # hz
     joints:
        - joint_0
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        - joint_7
        - headjoint_8
        - headjoint_9
